language: python

jobs:
  include:
    - env: TOXENV=py27
      python: '2.7'
    - env: TOXENV=py34
      python: '3.4'
    - env: TOXENV=py35
      python: '3.5'
    - env: TOXENV=py36
      python: '3.6'

install:
 - sudo apt-get update
 - sudo apt-get install libboost-test-dev
 - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
 - tar -zxvf release-1.8.0.tar.gz
 - "cd googletest-release-1.8.0/googletest && cmake . && sudo make install; cd -"
 - rm -rf googletest-release-1.8.0
 - pip install tox coveralls

script:
 - scons -j4 -C tests
 - tox

after_success:
  - coveralls
